// Generated by build/build.mjs from tokens/: do not edit, change the tokens.
import CoreGraphics

/// The Estuary theme's tokens.
public enum Estuary {
    /// Page background.
    public static let backdrop = EstuaryColor(light: 0xF0F0E8, dark: 0x0E0E14)
    /// Second page background (same as backdrop today).
    public static let backdrop2 = EstuaryColor(light: 0xF0F0E8, dark: 0x0E0E14)
    /// Raised surface: panels, the editor's current line.
    public static let surface = EstuaryColor(light: 0xF7F7F1, dark: 0x13131C)
    /// Card background.
    public static let card = EstuaryColor(light: 0xE8E8DF, dark: 0x1A1A26)
    /// Card on a card, chips, selection.
    public static let card2 = EstuaryColor(light: 0xDCDCD2, dark: 0x242433)
    /// Text field background.
    public static let field = EstuaryColor(light: 0xFFFFFF, dark: 0x13131C)
    /// Hairline borders.
    public static let border = EstuaryColor(light: 0xD0D0C8, dark: 0x2A2A3A)
    /// Body text.
    public static let ink = EstuaryColor(light: 0x111111, dark: 0xE4E4EC)
    /// Secondary text.
    public static let inkSoft = EstuaryColor(light: 0x333330, dark: 0xC4C4D0)
    /// Hints and captions (4.5:1 on every surface).
    public static let muted = EstuaryColor(light: 0x55554E, dark: 0x8C8CA2)
    /// Dividers, drawn over any surface.
    public static let line = EstuaryColor(light: 0x111111, lightAlpha: 0.08, dark: 0xFFFFFF, darkAlpha: 0.08)
    /// The lime: a fill, or text on dark surfaces, never text on light ones.
    public static let accent = EstuaryColor(light: 0xB9FF66, dark: 0xB9FF66)
    /// Pressed or hovered lime.
    public static let accentDeep = EstuaryColor(light: 0x9DE049, dark: 0x9DE049)
    /// A lime tint behind content.
    public static let accentSoft = EstuaryColor(light: 0xB9FF66, lightAlpha: 0.35, dark: 0xB9FF66, darkAlpha: 0.14)
    /// The accent as text and icons (4.5:1 on every surface).
    public static let accentText = EstuaryColor(light: 0x356509, dark: 0xB9FF66)
    /// Text on a lime fill.
    public static let onAccent = EstuaryColor(light: 0x111111, dark: 0x111111)
    /// Progress bars, the cursor.
    public static let progress = EstuaryColor(light: 0x111111, dark: 0xB9FF66)
    /// Focus rings.
    public static let focus = EstuaryColor(light: 0x111111, dark: 0xB9FF66)
    /// Deprecated (Myna's first palette): use dark.
    public static let navy = EstuaryColor(light: 0x111111, dark: 0x0E0E14)
    /// Deprecated (Myna's first palette): use on-dark.
    public static let cream = EstuaryColor(light: 0xF0F0E8, dark: 0xE4E4EC)
    /// Text on the dark bands of a light page.
    public static let onDark = EstuaryColor(light: 0xF0F0E8, dark: 0xF0F0E8)
    /// Secondary text on dark bands.
    public static let onDarkMuted = EstuaryColor(light: 0xA3A39B, dark: 0xA3A39B)
    /// Dark band background.
    public static let dark = EstuaryColor(light: 0x111111, dark: 0x07070B)
    /// Dark band, raised.
    public static let dark2 = EstuaryColor(light: 0x1C1C1C, dark: 0x13131C)
    /// Dark band, card.
    public static let dark3 = EstuaryColor(light: 0x2A2A2A, dark: 0x242433)
    /// Success text and badges.
    public static let ok = EstuaryColor(light: 0x146B50, dark: 0x34D399)
    /// Warnings.
    public static let warn = EstuaryColor(light: 0x725200, dark: 0xFBBF24)
    /// Errors and destructive actions.
    public static let danger = EstuaryColor(light: 0xA82C23, dark: 0xF87171)
    /// Information, neutral states.
    public static let info = EstuaryColor(light: 0x1F62A0, dark: 0x60A5FA)

    /// Corner radii, in points.
    public enum Radius {
        public static let xl: CGFloat = 34
        public static let lg: CGFloat = 26
        public static let md: CGFloat = 18
        public static let pill: CGFloat = 999
    }

    /// The typeface's family name (the app ships the font: Outfit, SIL OFL).
    public static let fontFamily = "Outfit"
}
